#version: '3.8'

services:
  mongodb:
    image: mongo:latest
    restart: unless-stopped
    container_name: urls-mongodb
    ports:
      - "27018:27017"
    volumes:
      - db_data:/data/db
    networks:
      - spring-boot-app

  redis:
    image: redis:latest
    container_name: redis
    restart: unless-stopped
    ports:
      - "6380:6379"
    volumes:
      - redis_data:/data
    networks:
      - spring-boot-app

  url-shortener:
    container_name: url-shortener-app
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8081:8080"
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/urls
      - SPRING_ZOOKEEPER_SERVERS=zookeeper:2181
      - SPRING_REDIS
    depends_on:
      - mongodb
      - zookeeper
      - redis
    networks:
      - spring-boot-app



  nginx:
    image: nginx:latest
    container_name: nginx
    ports:
      - "81:80"
    volumes:
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/html:/usr/share/nginx/html

    depends_on:
      - url-shortener
    networks:
      - spring-boot-app

  zookeeper:
    image: zookeeper:latest
    container_name: zookeeper
    restart: unless-stopped
    ports:
      - "2182:2181"
    environment:
      ZOO_MY_ID: 1
      ZOO_SERVERS: server.1=zookeeper:2888:3888
    volumes:
      - zookeeper_data:/data
      - zookeeper_datalog:/datalog
    networks:
      - spring-boot-app

volumes:
  redis_data:
  db_data:
  zookeeper_data:
  zookeeper_datalog:

networks:
  spring-boot-app:
