spring:
  application:
    name: URLShortener
  datasource:
    username: momen
    password: Iloveprogramming20@
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/urls
  jpa:
    hibernate:
      ddl-auto: update
  data:
    redis:
      host: localhost
      port: 6379
  cache:
    type: redis