spring:
  application:
    name: URLShortener
  data:
    mongodb:
      uri: mongodb://localhost:27017/urls
    redis:
      host: localhost
      port: 6379
  cache:
    type: redis

logging:
  level:
    org.springframework.cache: TRACE
server:
  port: 8080

zookeeper:
  host: 2182:2181
  timeout: 4000
  node-path: "/counter"
  range-length: 100000
  max-retry: 3
  session-timeout: 12000
